---
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.nxos.nxos

ansible_user: "{{ vault_lab_username }}"
ansible_password: "{{ vault_lab_password }}"

ansible_command_timeout: 90
ansible_connect_timeout: 30

fabric_name: nxos_multisite_evpn_lab
fabric_site: multisite_lab

evidence_root: evidence_pack
raw_evidence_dir: raw
report_evidence_dir: reports

vxlan_evpn_command_sets:
  platform:
    - show version
    - show running-config | include ^hostname
    - show feature
    - show interface brief
    - show ip interface brief vrf all
    - show vrf

  underlay:
    - show ip ospf neighbors
    - show ip route
    - show ip route vrf all
    - show ip pim neighbor
    - show ip pim interface

  bgp_evpn:
    - show bgp l2vpn evpn summary
    - show bgp l2vpn evpn
    - show bgp l2vpn evpn route-type 2
    - show bgp l2vpn evpn route-type 5

  vxlan_nve:
    - show nve peers
    - show nve vni
    - show interface nve1
    - show running-config interface nve1

  vlan_vni_vrf:
    - show vlan brief
    - show vn-segment
    - show vrf
    - show running-config bgp
    - show running-config | section nv overlay

  host_learning:
    - show mac address-table
    - show l2route evpn mac all
    - show ip arp vrf all
