---
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.nxos.nxos

ansible_user: "{{ vault_lab_username }}"
ansible_password: "{{ vault_lab_password }}"

ansible_command_timeout: 90
ansible_connect_timeout: 30

fabric_name: nxos_multisite_evpn_lab
fabric_site: multisite_lab

evidence_root: evidence_pack
raw_evidence_dir: raw
report_evidence_dir: reports

